# YAML Template for Governance Documents
# Use this template for constitution, protocols, standards

metadata:
  type: "governance"
  name: "[Document Name]"
  version: "1.0.0"
  created: "YYYY-MM-DD"
  lastUpdated: "YYYY-MM-DD"

lifecycle:
  currentStage: "discovery" # discovery | research | analysis | design | implementation | validation | delivery | closure
  status: "in-progress" # in-progress | complete | blocked | deferred
  nextStage: "[Next Stage]"
  blockers: []

humanInterface:
  checkpointRequired: true # true | false
  nextCheckpoint: "[What human needs to approve]"
  humanRole: "[Why human is needed]"
  context: "[Background for decision]"
  estimatedTime: "[Optional: e.g., 15 minutes]"

# Governance-specific content
rules:
  - id: 1
    name: "[Rule Name]"
    description: "[What this rule requires]"
    enforcement: "[How it's enforced]"
    violations:
      - "[What happens if violated]"
    examples:
      good: "[Example of following rule]"
      bad: "[Example of violating rule]"

triggers:
  - trigger: "![command]"
    meaning: "[What this trigger means]"
    purpose: "[Why it exists]"
    aiActions:
      - "[Action 1]"
      - "[Action 2]"
    behaviorChange:
      from: "[Previous behavior]"
      to: "[New behavior]"
    constraints:
      - "[Constraint 1]"
      - "[Constraint 2]"

principles:
  - principle: "[Principle name]"
    description: "[What it means]"
    rationale: "[Why it matters]"
    application: "[How to apply]"
