# YAML Template for Workflow Documents
# Use this template for !pulse, RRMD+, phase-closure, etc.

metadata:
  type: "workflow"
  name: "[Workflow Name]"
  version: "1.0.0"
  created: "YYYY-MM-DD"
  lastUpdated: "YYYY-MM-DD"

lifecycle:
  currentStage: "discovery"
  status: "in-progress"
  nextStage: "[Next Stage]"
  blockers: []

humanInterface:
  checkpointRequired: true
  nextCheckpoint: "[What human needs to approve]"
  humanRole: "[Why human is needed]"
  context: "[Background for decision]"

# Workflow-specific content
trigger:
  command: "![trigger]"
  meaning: "[What this trigger means]"
  purpose: "[Why it exists]"

workflow:
  name: "[Workflow Name]"
  purpose: "[What this workflow does]"
  
  steps:
    - step: 1
      action: "[Action name]"
      instruction: "[What to do]"
      required: true # true | false
      validation: "[How to verify completion]"
    
    - step: 2
      action: "[Action name]"
      instruction: "[What to do]"
      required: true
      validation: "[How to verify completion]"
  
  output:
    format: "[What format to produce]"
    deliverable: "[What to deliver]"
    waitFor: "[What to wait for]"
  
  constraints:
    - "[Constraint 1]"
    - "[Constraint 2]"
  
  selfInvokeCriteria:
    - condition: "[When to self-invoke]"
      reason: "[Why to self-invoke]"
